"""Create new konsolidasi_log table

Revision ID: aaf95cb3591a
Revises: 
Create Date: 2024-11-21 13:28:59.170417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aaf95cb3591a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konsolidasi_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_running', sa.Date(), nullable=True),
    sa.Column('time_running', sa.Time(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Double(), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('konsolidasi_log_example')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konsolidasi_log_example',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date_running', sa.DATE(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('time_running', mysql.TIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('message', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rows_fetched', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rows_inserted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('runtime', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('job_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('flag', mysql.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('konsolidasi_log')
    # ### end Alembic commands ###
