"""Create table for konsolidasi_log

Revision ID: b5301a17a173
Revises: 
Create Date: 2024-11-22 14:15:05.727325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5301a17a173'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konsolidasi_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_running', sa.Date(), nullable=True),
    sa.Column('time_running', sa.Time(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Double(), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('konsolidasi_log')
    # ### end Alembic commands ###
